# Generated by Django 4.1.5 on 2023-01-25 14:12

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_attachementsimages_alter_feuille_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachementsimages',
            name='image',
            field=models.ImageField(upload_to=ticket.models.image_path),
        ),
    ]
