# Generated by Django 4.1.5 on 2023-01-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_attachementimagearticle_attachementimageticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdecaisse',
            name='attachement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.attachementimageticket'),
        ),
    ]
