# Generated by Django 4.1.5 on 2023-01-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticketdecaisse_attachement'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemarticle',
            name='attachement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.attachementimagearticle'),
        ),
    ]
