# Generated by Django 4.1.5 on 2023-02-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_attachementimagearticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachementimageticket',
            name='type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('recepiece', 'Receipiece'), ('facture', 'Facture')], default='ticket', max_length=10),
            preserve_default=False,
        ),
    ]
