# Generated by Django and I, 4.1.5 on 2023-02-06 07:28

from django.db import migrations, models

def alter_duplicates(apps, schema):
    itemarticles = apps.get_model('ticket', 'ItemArticle')
    articles = apps.get_model('ticket', 'article')
    
    for article in articles.objects.all():
        item_article_ident = article.item.ident
        unique_item_article = itemarticles.objects.filter(ident=item_article_ident).last()
        
        if unique_item_article is None:
            raise ValueError(f"{item_article_ident} is not in itemarticle table...")
        
        articles.objects.filter(id=article.id).update(item_id=unique_item_article.id)
    
        
class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_article_price'),
    ]

    operations = [
        migrations.RunPython(code=alter_duplicates),
    ]
