# Generated by Django and I, 4.1.5 on 2023-02-06 07:28

from django.db import migrations, models

def remove_duplicates(apps, schema):
    itemarticles = apps.get_model('ticket', 'ItemArticle')
    articles = apps.get_model('ticket', 'article')
    
    for ia in itemarticles.objects.all():
        article = articles.objects.filter(item=ia).first()
        
        if article is None:
            itemarticles.objects.get(id=ia.id).delete()
    
        
class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_remove_duplicate_on_item_article'),
    ]

    operations = [
        migrations.RunPython(code=remove_duplicates),
    ]
