# Generated by Django and I, 4.1.5 on 2023-02-06 07:28

from django.db import migrations, models
from ticket.models import *


def ticketdecaisseshop_migration(apps, schema):    
    ticketdecaisses = apps.get_model('ticket', 'TicketDeCaisse')
    shops = apps.get_model('ticket', 'TicketDeCaisseShopEnum')
    localisations = apps.get_model('ticket', 'TicketDeCaisseLocalisationEnum')
    
    for tdc in ticketdecaisses.objects.all():
        tdc.shop.ident = ''
        tdc.shop.city = ''
        tdc.shop.localisation = tdc.localisation.name
        tdc.shop.save(force_update=True)
    
class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_ticketdecaisseshopenumenum_city_and_more'),
    ]

    operations = [
        migrations.RunPython(code=ticketdecaisseshop_migration),
    ]
