# Generated by Django 4.1.5 on 2023-03-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_ticketdecaisseshop_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdecaisse',
            name='localisation',
        ),
        migrations.AddField(
            model_name='ticketdecaissetypeenum',
            name='description',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='TicketDeCaisseLocalisationEnum',
        ),
    ]
