# Generated by Django 4.1.5 on 2023-03-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('ticket', '0022_profile_userapikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey'),
        ),
        migrations.AddField(
            model_name='factures',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey'),
        ),
        migrations.AddField(
            model_name='feuille',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey'),
        ),
        migrations.AddField(
            model_name='ticketdecaisse',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey'),
        ),
    ]
