# Generated by Django 4.1.5 on 2023-03-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('ticket', '0023_article_api_key_factures_api_key_feuille_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachementimageticket',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey'),
        ),
        migrations.AlterField(
            model_name='ticketdecaisse',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
