# Generated by Django 4.1.5 on 2023-03-28 10:17
import math

from django.db import migrations, models

def fill_out_new_fields_then_clean_recepieces_articles(apps, schema):
    tdcs = apps.get_model('ticket', 'TicketDeCaisse')
    articles = apps.get_model('ticket', 'article')
    
    for tdc in tdcs.objects.all():
        ars = articles.objects.filter(tdc=tdc)
        if len(ars) == 1:
            tdc.total = ars.first().price
            tdc.type = 'recepiece'
        else:
            tdc.total = round(math.fsum([(a.price * a.quantity) - a.remise for a in ars]), 2)
            tdc.type = 'ticket'
        tdc.save(force_update=True)

class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0026_itemarticlebrandenum_itemarticle_ean13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdecaisse',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ticketdecaisse',
            name='type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('recepiece', 'Receipiece'), ('facture', 'Facture')], default='ticket', max_length=10),
            preserve_default=False,
        ),
        migrations.RunPython(code=fill_out_new_fields_then_clean_recepieces_articles),
    ]
