# Generated by Django 4.1.5 on 2023-04-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_ticketdecaisse_total_ticketdecaisse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdecaisseshopenum',
            name='valide',
            field=models.BooleanField(default=True),
        ),
    ]
