# Generated by Django 4.1.5 on 2023-05-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0029_ticketdecaisse_remise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachementimagearticle',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemarticle',
            options={'ordering': ['ident']},
        ),
        migrations.AlterModelOptions(
            name='itemarticlebrandenum',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemarticlecategoryenum',
            options={'ordering': ['name', 'required']},
        ),
        migrations.AlterModelOptions(
            name='itemarticlegroupenum',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='itemarticle',
            name='attachement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.attachementimagearticle'),
        ),
        migrations.AlterField(
            model_name='itemarticle',
            name='brand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.itemarticlebrandenum'),
        ),
        migrations.AlterField(
            model_name='itemarticle',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.itemarticlecategoryenum'),
        ),
        migrations.AlterField(
            model_name='itemarticle',
            name='ean13',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ItemArticleToGS1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean13', models.TextField(default=None)),
                ('ident', models.TextField(unique=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ticketdecaisseshopenum')),
            ],
            options={
                'ordering': ['ident'],
            },
        ),
    ]
