# Generated by Django 4.1.5 on 2023-05-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0030_alter_attachementimagearticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemarticle',
            name='junkscore',
            field=models.CharField(choices=[('0', 'No Value'), ('1', 'OK'), ('2', 'COULD BE AVOIDED'), ('3', 'SHOULD BE AVOIDED'), ('4', 'MUST BE AVOIDED')], default='0', max_length=1, null=True),
        ),
    ]
