# Generated by Django 4.1.5 on 2023-05-22 11:29

from django.db import migrations, models
import django.db.models.deletion
import ticket.storage.jpegStorage


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_itemarticle_junkscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopEnseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.ImageField(storage=ticket.storage.jpegStorage.JpegStorage(bucket_name='enseignes'), upload_to='enseignes')),
            ],
        ),
        migrations.AlterModelOptions(
            name='itemarticletogs1',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='ticketdecaisseshopenum',
            name='enseigne',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.shopenseigne'),
        ),
    ]
