# Generated by Django 4.1.5 on 2023-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_alter_ticketdecaisseshopenum_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdecaisse',
            name='need_to_be_validated',
            field=models.BooleanField(default=False),
        ),
    ]
