# Generated by Django 4.1.5 on 2023-05-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0034_ticketdecaisse_need_to_be_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachementimageticket',
            name='type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('recepiece', 'Receipiece'), ('facture', 'Facture')], max_length=10, null=True),
        ),
    ]
