# Generated by Django 4.1.5 on 2023-05-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('ticket', '0035_alter_attachementimageticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnvalidatedTicketDeCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField()),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey')),
            ],
        ),
        migrations.RemoveField(
            model_name='userapikey',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserApiKey',
        ),
    ]
