# Generated by Django 4.1.5 on 2023-06-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0037_alter_attachementimageticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLAttachementTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_datas', models.TextField()),
                ('attachement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.attachementimageticket')),
            ],
            options={
                'ordering': ['id', 'attachement'],
            },
        ),
        migrations.DeleteModel(
            name='UnvalidatedTicketDeCaisse',
        ),
    ]
