# Generated by Django 4.1.5 on 2023-06-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0038_mlattachementticket_delete_unvalidatedticketdecaisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlattachementticket',
            name='attachement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.attachementimageticket', unique=True),
        ),
    ]
