# Generated by Django 4.1.5 on 2023-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0041_mlattachementticket_valide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlattachementticket',
            options={'ordering': ['id', 'valide', 'attachement']},
        ),
        migrations.AddField(
            model_name='mlattachementticket',
            name='gcp_datas',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
