# Generated by Django 4.1.5 on 2023-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0042_alter_mlattachementticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlattachementticket',
            name='gcp_datas',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='mlattachementticket',
            name='json_datas',
            field=models.JSONField(),
        ),
    ]
