# Generated by Django 4.1.5 on 2023-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0043_alter_mlattachementticket_gcp_datas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenon', models.TextField()),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
